name: Publish

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: windows-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3

            - name: Get version
              id: version
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: Flow.Launcher.Plugin.IPDetails/plugin.json
                  prop_path: Version

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.x

            - name: Build
              shell: pwsh
              run: |
                  dotnet publish Flow.Launcher.Plugin.IPDetails/Flow.Launcher.Plugin.IPDetails.csproj -c Release -o "Flow.Launcher.Plugin.IPDetails"
                  Compress-Archive -Path Flow.Launcher.Plugin.IPDetails/Flow.Launcher.Plugin.IPDetails/Flow.Launcher.Plugin.IPDetails/* -DestinationPath Flow.Launcher.Plugin.IPDetails.zip -Force

            - name: Publish
              uses: softprops/action-gh-release@v1
              with:
                  files: Flow.Launcher.Plugin.IPDetails.zip
                  tag_name: v${{steps.version.outputs.prop}}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
